services:
  - type: web
    name: nyx-backend
    env: node
    rootDir: backend
    buildCommand: npm install
    startCommand: npm run dev
    envVars:
      - key: NODE_ENV
        value: production

  - type: web
    name: nyx-frontend
    env: static
    rootDir: frontend
    buildCommand: npm run build
    staticPublishPath: dist
